import fs from "node:fs/promises";
import path from "node:path";
import { SupervisorConfig } from "../types";
import { ensureDir, truncate } from "../utils";

export interface MemoryArtifacts {
  contextIndexPath: string;
  agentsPath: string;
  alwaysReadFiles: string[];
  onDemandFiles: string[];
}

function safeSlug(input: string): string {
  return input.replace(/[^a-zA-Z0-9._-]+/g, "-");
}

function artifactDir(config: SupervisorConfig, issueNumber: number): string {
  return path.join(path.dirname(config.stateFile), "memory", safeSlug(config.repoSlug), `issue-${issueNumber}`);
}

function summarizeText(content: string, maxLength = 320): string {
  const stripped = content
    .replace(/```[\s\S]*?```/g, " ")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line !== "" && !line.startsWith("#"))
    .slice(0, 8)
    .join(" ");

  return truncate(stripped, maxLength) ?? "No summary text extracted.";
}

function extractHeadings(content: string, maxHeadings = 8): string[] {
  return content
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => /^#{1,6}\s+/.test(line))
    .slice(0, maxHeadings);
}

async function readWorkspaceMemoryFile(workspacePath: string, relativePath: string): Promise<{
  absolutePath: string;
  exists: boolean;
  summary: string;
  headings: string[];
}> {
  const absolutePath = path.resolve(workspacePath, relativePath);
  try {
    const content = await fs.readFile(absolutePath, "utf8");
    return {
      absolutePath,
      exists: true,
      summary: summarizeText(content),
      headings: extractHeadings(content),
    };
  } catch (error) {
    const maybeErr = error as NodeJS.ErrnoException;
    if (maybeErr.code === "ENOENT") {
      return {
        absolutePath,
        exists: false,
        summary: "File not found in this workspace.",
        headings: [],
      };
    }

    return {
      absolutePath,
      exists: false,
      summary: `Unable to read file: ${maybeErr.code ?? "unknown_error"}.`,
      headings: [],
    };
  }
}

function buildContextIndex(args: {
  repoSlug: string;
  sharedFiles: Array<{
    relativePath: string;
    absolutePath: string;
    exists: boolean;
    summary: string;
    headings: string[];
  }>;
  journalPath: string;
  agentsPath: string;
}): string {
  const { repoSlug, sharedFiles, journalPath, agentsPath } = args;
  const sections = sharedFiles.map((file) =>
    [
      `## ${file.relativePath}`,
      `- Absolute path: ${file.absolutePath}`,
      `- Exists in current workspace: ${file.exists ? "yes" : "no"}`,
      `- Summary: ${file.summary}`,
      ...(file.headings.length > 0 ? ["- Headings:", ...file.headings.map((heading) => `  - ${heading}`)] : ["- Headings: none extracted"]),
      "",
    ].join("\n"),
  );

  return [
    `# Context Index for ${repoSlug}`,
    "",
    "This file is generated by opencode-supervisor to reduce prompt size and file fan-out.",
    "",
    "Read order:",
    `1. ${agentsPath}`,
    `2. ${journalPath}`,
    "3. Only open one or two shared memory files from the list below if the current issue actually needs them.",
    "",
    ...sections,
  ].join("\n");
}

function buildAgentsFile(args: {
  repoSlug: string;
  journalPath: string;
  contextIndexPath: string;
  onDemandFiles: string[];
}): string {
  const { repoSlug, journalPath, contextIndexPath, onDemandFiles } = args;
  return [
    `# AGENTS.generated.md for ${repoSlug}`,
    "",
    "This file is generated by opencode-supervisor. It defines the memory read policy for agent turns.",
    "",
    "## Always Read First",
    `- ${contextIndexPath}`,
    `- ${journalPath}`,
    "",
    "## On-Demand Durable Memory",
    ...onDemandFiles.map((filePath) => `- ${filePath}`),
    "",
    "## Policy",
    "- Do not bulk-read every durable memory file on every turn.",
    "- Use the context index to decide which one or two files are relevant to the current issue.",
    "- Prefer the issue journal for the latest hypothesis, exact failure, commands run, and next actions.",
    "- Prefer focused commands and focused file reads over broad repo exploration.",
    "",
    "## Integration with opencode",
    "This supervisor integrates with oh-my-opencode plugin.",
    "- Use /init-deep to initialize hierarchical AGENTS.md knowledge base",
    "- The context index above supplements opencode's built-in context management",
    "- Session continuity is handled via opencode's task() session_id",
  ].join("\n");
}

export async function syncMemoryArtifacts(args: {
  config: SupervisorConfig;
  issueNumber: number;
  workspacePath: string;
  journalPath: string;
}): Promise<MemoryArtifacts> {
  const { config, issueNumber, workspacePath, journalPath } = args;
  const dirPath = artifactDir(config, issueNumber);
  await ensureDir(dirPath);

  const sharedFiles = await Promise.all(
    config.sharedMemoryFiles.map(async (relativePath) => ({
      relativePath,
      ...(await readWorkspaceMemoryFile(workspacePath, relativePath)),
    })),
  );

  const contextIndexPath = path.join(dirPath, "context-index.md");
  const agentsPath = path.join(dirPath, "AGENTS.generated.md");
  const onDemandFiles = sharedFiles.map((file) => file.absolutePath);

  const contextIndex = buildContextIndex({
    repoSlug: config.repoSlug,
    sharedFiles,
    journalPath,
    agentsPath,
  });
  const agentsFile = buildAgentsFile({
    repoSlug: config.repoSlug,
    journalPath,
    contextIndexPath,
    onDemandFiles,
  });

  await fs.writeFile(contextIndexPath, `${contextIndex}\n`, "utf8");
  await fs.writeFile(agentsPath, `${agentsFile}\n`, "utf8");

  return {
    contextIndexPath,
    agentsPath,
    alwaysReadFiles: [agentsPath, contextIndexPath, journalPath],
    onDemandFiles,
  };
}
